{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bottlerocket.automation",
    "module": "automation_library",
    "version": "3.2.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "vchc67yoczge7jgjfehewqdyoy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "automation_library-3.2.4-SNAPSHOT.jar",
          "url": "automation_library-3.2.4-SNAPSHOT.jar",
          "size": 478597,
          "sha512": "4dfecb15b8fcbdcba86ee98506d63e6744a846500422f3012cda05544e588a4e8ed8b541046173ab976fb8529cccabf8c5ad84f061b5eb1deeaf522e5f87199e",
          "sha256": "f853ecda1aa5592baaf8825d71358a23ce0af13c9e5a2a6bc3c05bf2fb2198d1",
          "sha1": "e2d87131a9f3572dc2e5579e23a3b9be91fa3183",
          "md5": "ed0f2513088f8e5570bd7721881ee189"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "3.0.9"
          }
        },
        {
          "group": "org.testng",
          "module": "testng",
          "version": {
            "requires": "7.7.1"
          }
        },
        {
          "group": "org.seleniumhq.selenium",
          "module": "selenium-java",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "io.appium",
          "module": "java-client",
          "version": {
            "requires": "8.1.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.0.0-alpha.14"
          }
        },
        {
          "group": "org.apache.poi",
          "module": "poi-ooxml",
          "version": {
            "requires": "5.2.5"
          }
        },
        {
          "group": "com.aventstack",
          "module": "extentreports",
          "version": {
            "requires": "4.0.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.13"
          }
        },
        {
          "group": "com.monitorjbl",
          "module": "xlsx-streamer",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.mock-server",
          "module": "mockserver-core",
          "version": {
            "requires": "5.6.1"
          }
        },
        {
          "group": "org.mock-server",
          "module": "mockserver-client-java",
          "version": {
            "requires": "5.6.1"
          }
        },
        {
          "group": "org.mock-server",
          "module": "mockserver-netty",
          "version": {
            "requires": "5.6.1"
          }
        },
        {
          "group": "io.appium",
          "module": "mitmproxy-java",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.mashape.unirest",
          "module": "unirest-java",
          "version": {
            "requires": "1.4.9"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongo-java-driver",
          "version": {
            "requires": "3.12.9"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-jackson",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "3.14.7"
          }
        }
      ],
      "files": [
        {
          "name": "automation_library-3.2.4-SNAPSHOT.jar",
          "url": "automation_library-3.2.4-SNAPSHOT.jar",
          "size": 478597,
          "sha512": "4dfecb15b8fcbdcba86ee98506d63e6744a846500422f3012cda05544e588a4e8ed8b541046173ab976fb8529cccabf8c5ad84f061b5eb1deeaf522e5f87199e",
          "sha256": "f853ecda1aa5592baaf8825d71358a23ce0af13c9e5a2a6bc3c05bf2fb2198d1",
          "sha1": "e2d87131a9f3572dc2e5579e23a3b9be91fa3183",
          "md5": "ed0f2513088f8e5570bd7721881ee189"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "automation_library-3.2.4-SNAPSHOT-sources.jar",
          "url": "automation_library-3.2.4-SNAPSHOT-sources.jar",
          "size": 508882,
          "sha512": "e8c3259973200de2534dc9ce095bab9c9a8472e57c4d9ce5604853431fa5fedef2b6557ce0dbe837d9264376f5732e6e3bca2368dacff92816c3f8182baae452",
          "sha256": "b51696a112cb0d32fdfdb21d55eff1ed4f62983c10552dcbf0e52cb65bd223ab",
          "sha1": "e5a53a0e676288f7292c7673f34b4451317b617f",
          "md5": "2c8badfeb48e10fc3a35c66ce28d4283"
        }
      ]
    }
  ]
}
