{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bottlerocket.automation",
    "module": "automation_library",
    "version": "3.2.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "5qx5c7wcrbhizex4wqajj7u3lu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "automation_library-3.2.3-SNAPSHOT.jar",
          "url": "automation_library-3.2.3-SNAPSHOT.jar",
          "size": 478565,
          "sha512": "04601156e8a52e4bf83e8d5ab658bd37dcd15a05d527c66a6b2f9ed176dd2151aba11fe0bf02be2772e1481c25454cc06f353097ef13300e7a1c533441d3c114",
          "sha256": "f39b0a10e11bb5265e0673a91514efc0a8f6d41249ceca7a22ff672afa3b59cb",
          "sha1": "80ccda8454f8b1eb8cdfe8738c963da3b2b7d488",
          "md5": "0f03d91c8eab20d8105082be9363ffc4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "3.0.9"
          }
        },
        {
          "group": "org.testng",
          "module": "testng",
          "version": {
            "requires": "7.7.1"
          }
        },
        {
          "group": "org.seleniumhq.selenium",
          "module": "selenium-java",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "io.appium",
          "module": "java-client",
          "version": {
            "requires": "8.1.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.0.0-alpha.14"
          }
        },
        {
          "group": "org.apache.poi",
          "module": "poi-ooxml",
          "version": {
            "requires": "5.2.5"
          }
        },
        {
          "group": "com.aventstack",
          "module": "extentreports",
          "version": {
            "requires": "4.0.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.13"
          }
        },
        {
          "group": "com.monitorjbl",
          "module": "xlsx-streamer",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.mock-server",
          "module": "mockserver-core",
          "version": {
            "requires": "5.6.1"
          }
        },
        {
          "group": "org.mock-server",
          "module": "mockserver-client-java",
          "version": {
            "requires": "5.6.1"
          }
        },
        {
          "group": "org.mock-server",
          "module": "mockserver-netty",
          "version": {
            "requires": "5.6.1"
          }
        },
        {
          "group": "io.appium",
          "module": "mitmproxy-java",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.mashape.unirest",
          "module": "unirest-java",
          "version": {
            "requires": "1.4.9"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongo-java-driver",
          "version": {
            "requires": "3.12.9"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-jackson",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "3.14.7"
          }
        }
      ],
      "files": [
        {
          "name": "automation_library-3.2.3-SNAPSHOT.jar",
          "url": "automation_library-3.2.3-SNAPSHOT.jar",
          "size": 478565,
          "sha512": "04601156e8a52e4bf83e8d5ab658bd37dcd15a05d527c66a6b2f9ed176dd2151aba11fe0bf02be2772e1481c25454cc06f353097ef13300e7a1c533441d3c114",
          "sha256": "f39b0a10e11bb5265e0673a91514efc0a8f6d41249ceca7a22ff672afa3b59cb",
          "sha1": "80ccda8454f8b1eb8cdfe8738c963da3b2b7d488",
          "md5": "0f03d91c8eab20d8105082be9363ffc4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "automation_library-3.2.3-SNAPSHOT-sources.jar",
          "url": "automation_library-3.2.3-SNAPSHOT-sources.jar",
          "size": 508822,
          "sha512": "819de5e201af1dbbf72d7f90d5cd89580db1f14c13e3264656dd61221e3d531dfe19dec553a926885f0b3ac0d37c96c0bcb59e1ee1e59af4d1c618dd1974ffaa",
          "sha256": "75e8db92495d6b6f1a41f8a4974e5e1c3255e4192c2243756aee708cb16a5aa9",
          "sha1": "fe090373f53ab1def31c890d5c1f224666661db7",
          "md5": "ec8b9d991e980cba5db38fee9c76397a"
        }
      ]
    }
  ]
}
